package com.pventafe.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
public class Arpfoe {
    private String noCia;
    private String noOrden;
    private String grupo;
    private String noCliente;
    private String division;
    private String noVendedor;
    private String codTped;
    private String codFpago;
    private String fRecepcion;
    private String fechaRegistro;
    private String fAprobacion;
    private String fechaEntrega;
    private String fechaEntregaReal;
    private String fechaVence;
    private String tipoPrecio;
    private String moneda;
    private double subTotal;
    private double tImpuesto;
    private double tPrecio;
    private double impuesto;
    private String estado;
    private String bodega;
    private String cuser;
    private double igv;
    private String indGuiado;
    private String direccionComercial;
    private String motivoTraslado;
    private String nombreCliente;
    private String ruc;
    private double tDescuento;
    private String tipoDocRef;
    private String codClasPed;
    private String tipoFpago;
    private double tDsctoGlobal;
    private double tValorVenta;
    private String codTienda;
    private String nombTienda;
    private String direcTienda;
    private String almaOrigen;
    private String almaDestino;
    private String tipoArti;
    private String tipoDocCli;
    private String numDocCli;
    private String codDirEntrega;
    private String codDirSalida;
    private String noClienteSalida;
    private String estadoAsignacion;
    private String listaPrecAnt;
    private String usuarioAprod;
    private String indVtaAnticipada;
    private double totalBruto;
    private String codTPed1;
    private String codTpedb;
    private String codTpedn;
    private String tipo;
    private String indPvent;
    private String centro;
    private String indFactura1;
    private String indBoleta1;
    private String codCaja;
    private String cajera;
    private String convenio;
    private String centroCosto;
    private String indNotaCred;
    private String indExportacion;
    private String consumo;
    private String indFerias;
    private String indProvincia;
    private double redondeo;
    private String indCodBarra;
    private String indFactTexto;
    private String indGuiaTexto;
    private String facturaTexto;
    private double impuestoFlete;
    private String onLine;
    private String contNeto;
    private String indProforma1;
    private double aCta;
    private String entrega;
    private String horaEntrega;
    private String indPideLote;
    private String motConting;
    private double operExoneradas;
    private double operGratuitas;
    private double operGravadas;
    private String tipoOperacion;
    private String guiaTemp;
    List<Arpfol> arpfolList;
}
