spring:
  application:
    name: pventafe

server:
  port: 8088

datasource:
  my_cnx_mysql:
    url: jdbc:mysql://localhost:3306/factura2023
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 20
    pool-name: "cnx-mysql"
    auto-commit: true
