spring:
  application:
    name: pventafe

server:
  port: 8088

datasource:
  my-oracle:
    jdbc-url: jdbc:oracle:thin:@//localhost:1521/BDNX1
    username: FACTU
    password: FACTU
    driver-class-name: oracle.jdbc.OracleDriver
    auto-commit: false
